-- TABELA USUARIOS
CREATE TABLE Usuario (
    ID INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Senha VARCHAR(10) NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY (ID, Email)
);

-- TABELA DIETA
CREATE TABLE Dieta (
    ID INT NOT NULL PRIMARY KEY,
    Horario VARCHAR(5) NOT NULL,
    Refeicao VARCHAR(100) NOT NULL,
    Observacao VARCHAR(100),
    FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID)
);

-- TABELA TREINO
CREATE TABLE Treino (
    ID INT NOT NULL PRIMARY KEY,
    Dia_Semana SMALLINT NOT NULL,
    Ordem INT(2) NOT NULL,
    Exercicio VARCHAR(50) NOT NULL,
    Descricao VARCHAR(50),
    FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID)
);

-- TABELA CALENDARIO
CREATE TABLE Calendario (
    ID INT NOT NULL PRIMARY KEY,
    Data DATE NOT NULL,
    Treino_Check BOOLEAN DEFAULT FALSE,
    Dieta_Check BOOLEAN DEFAULT FALSE,
    CONSTRAINT PK_Calendario PRIMARY KEY (ID, Data),
    FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID)
);